//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public University()
        {
            this.CoachORStaffs = new HashSet<CoachORStaff>();
        }
    
        public long UniversityID { get; set; }
        public string UniversityName { get; set; }
        public string UniversityURL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Title { get; set; }
        public string UniversityLogo { get; set; }
        public string UniversityLink { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UniversityKey { get; set; }
        public Nullable<bool> IsAdmission { get; set; }
        public string UniversityFullName { get; set; }
        public string State { get; set; }
        public Nullable<bool> DKIM { get; set; }
        public Nullable<long> IpedID { get; set; }
    
        public virtual ICollection<CoachORStaff> CoachORStaffs { get; set; }
    }
}
